# Generated by Django 3.2.2 on 2021-05-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210515_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.TextField(default='https://static.vecteezy.com/system/resources/thumbnails/002/275/816/small/cartoon-avatar-of-smiling-beard-man-profile-icon-vector.jpg', verbose_name='img'),
        ),
    ]
