# Generated by Django 3.2 on 2021-05-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkly', '0003_alter_parking_park_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='reservation_date',
        ),
    ]
