# Generated by Django 3.2 on 2021-05-11 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkly', '0005_auto_20210510_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='parking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='parkly.parking'),
        ),
    ]
