# Generated by Django 3.2.2 on 2021-05-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkly', '0006_alter_reservation_parking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='activated',
            new_name='is_email_verified',
        ),
    ]
