# Generated by Django 3.2.2 on 2021-05-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkly', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
