# Generated by Django 3.2.2 on 2021-05-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkly', '0011_auto_20210515_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ceated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
