# Generated by Django 3.2.2 on 2021-05-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkly', '0012_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='is_reentry_allowed',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='price',
        ),
        migrations.AddField(
            model_name='lot',
            name='is_reentry_allowed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
