# Generated by Django 3.2.2 on 2021-05-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkly', '0013_auto_20210519_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='location',
            field=models.CharField(max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Price per parking'),
        ),
    ]
