# Generated by Django 3.2.2 on 2021-05-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkly', '0014_auto_20210519_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='image',
            field=models.CharField(default='https://cache3.pakwheels.com/assets/dealers/original/missing.png', max_length=255, null=True),
        ),
    ]
