# Generated by Django 3.2.2 on 2021-05-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkly', '0015_alter_lot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
