# Generated by Django 3.2.3 on 2021-05-19 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkly', '0015_auto_20210519_1723'),
        ('parkly', '0016_alter_reservation_code'),
    ]

    operations = [
    ]
